# Generated by Django 4.2.6 on 2023-10-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('add_date',), 'verbose_name': 'Ediləcək iş', 'verbose_name_plural': 'Ediləcək işlər'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ediləcək iş'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('Hələ başlanmayıb', 'not'), ('Davam edir', 'progress'), ('Bitib', 'finish')], default='Hələ başlanmayıb', max_length=255, null=True, verbose_name='Taskin statusu'),
        ),
    ]
